services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    user: mysql
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 3306
    restart: always
    env_file:
      - path: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    container_name: redis
    hostname: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 6379
    restart: always

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 9000
    restart: always
    env_file:
      - path: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    env_file:
      - path: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/database'

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  credentials:
    file: ./secrets/credentials.txt