services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 3306
    restart: always
    env_file:
      - path: .env
        required: true
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 9000
    restart: always
    env_file:
      - path: .env
        required: true
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - inception
    restart: always
    env_file:
      - path: .env
        required: true
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/mariadb'

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  credentials:
    file: ./secrets/credentials.txt